apiVersion: apps/v1
kind: Deployment
metadata:
  name: eee-deployment
  labels:
    app: eee
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: eee
  template:
    metadata:
      labels:
        app: eee
    spec:
      containers:
        - name: eee
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
