apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aaa
  template:
    metadata:
      labels:
        app: aaa
    spec:
      containers:
      - name: aaa
        image: imp2/standard-website:latest
        ports:
        - containerPort: 80
        - containerPort: 8081
