apiVersion: apps/v1
kind: Deployment
metadata:
  name: eee-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eee
  template:
    metadata:
      labels:
        app: eee
    spec:
      containers:
      - name: eee
        image: imp2/sonar-app:latest
        ports:
        - containerPort: 8085
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
