apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: aaa-bbb-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: imp2/standard-website:latest
          ports:
            - containerPort: 80
