apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaa-deployment
  labels:
    app: aaa
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aaa
  template:
    metadata:
      labels:
        app: aaa
    spec:
      containers:
        - name: aaa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80