apiVersion: v1
kind: Service
metadata:
  name: gradio-text-converter-service
  namespace: aaa-bbb-ns
spec:
  selector:
    app: gradio-text-converter
  ports:
    - protocol: TCP
      port: 7860
      targetPort: 7860
  type: ClusterIP
