apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website
  namespace: aaa-bbb-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
        - name: static-website
          image: imp2/standard-website:latest
          ports:
            - containerPort: 80
