apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ostk-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: charts/ostk-app
    repoURL: <DEIN_GIT_REPO_URL>
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
