apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bbb-app
  namespace: argocd
spec:
  destination:
    namespace: bbb-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/bbb
    repoURL: https://github.com/Impulsleistung/k8s.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
