apiVersion: v1
kind: Service
metadata:
  name: ccc-service
  labels:
    app: ccc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: ccc
