apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddd-deployment
  labels:
    app: ddd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ddd
  template:
    metadata:
      labels:
        app: ddd
    spec:
      containers:
        - name: ddd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
