apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbb-deployment
  labels:
    app: bbb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bbb
  template:
    metadata:
      labels:
        app: bbb
    spec:
      containers:
        - name: bbb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
