apiVersion: v1
kind: Service
metadata:
  name: bbb-service
  labels:
    app: bbb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7860
      protocol: TCP
      name: http
  selector:
    app: bbb
