replicaCount: 1

image:
  repository: imp2/standard-website
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: 29137147-cf8f-4673-a55a-028b2b89af31.lb.civo.com
  path: /
  annotations: {}

resources: {}
