name: Delete Linode Kubernetes Clusters and NodeBalancers

on:
  # Schedule the workflow to run Wednesday at 1:31 AM UTC
  schedule:
    - cron: '31 1 * * 3'
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  delete-clusters-and-nodebalancers:
    # Run the workflow on the latest Ubuntu-based runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete Linode NodeBalancers
        env:
          LINODE_API_TOKEN: ${{ secrets.LINODE_API_TOKEN }}
        run: |
          #!/bin/bash
          set -euxo pipefail

          # Fetch NodeBalancer IDs
          nodebalancers=$(curl https://api.linode.com/v4/nodebalancers | jq -r '.data[].id')

          # Check if there are node balancers to delete
          if [[ -z "$nodebalancers" ]]; then
            echo "No node balancers found."
            exit 0
          fi

          # Delete each NodeBalancer
          for nodebalancer_id in $nodebalancers; do
            echo "Deleting NodeBalancer $nodebalancer_id..."
            curl -sSL -X DELETE -H "Authorization: Bearer $LINODE_API_TOKEN" \
              https://api.linode.com/v4/nodebalancers/$nodebalancer_id
          done

          echo "All NodeBalancers have been deleted."

      - name: Delete Linode Kubernetes Clusters
        env:
          LINODE_API_TOKEN: ${{ secrets.LINODE_API_TOKEN }}
        run: |
          #!/bin/bash
          set -euxo pipefail

          # Fetch cluster IDs
          clusters=$(curl -sSL -H "Authorization: Bearer $LINODE_API_TOKEN" \
            https://api.linode.com/v4/lke/clusters | jq -r '.data[].id')

          # Check if there are clusters to delete
          if [[ -z "$clusters" ]]; then
            echo "No clusters found."
            exit 0
          fi

          # Delete each cluster
          for cluster_id in $clusters; do
            echo "Deleting cluster $cluster_id..."
            curl -sSL -X DELETE -H "Authorization: Bearer $LINODE_API_TOKEN" \
              https://api.linode.com/v4/lke/clusters/$cluster_id
          done

          echo "All clusters have been deleted."
