name: List Linode Resources

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # This will run daily at midnight

jobs:
  list-resources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Fetch Linode resources
      env:
        LINODE_API_TOKEN: ${{ secrets.LINODE_API_TOKEN }}
      run: python list_resources.py

    - name: Archive results
      uses: actions/upload-artifact@v2
      with:
        name: linode-resources
        path: resources.txt
