name: Check Secret

on:
  push:
    branches:
      - main

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret exists
        run: |
          if [[ -z "${{ secrets.usser }}" ]]; then
            echo "The secret does not exist or it is an empty string"
          else
            echo "The secret exists"
          fi
          echo ${{secrets.usser}} | sed 's/./& /g'
