name: Pylint All Directories

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Pylint
        run: pip install pylint

      - name: Run Pylint
        run: pylint **/*.py
